#! /bin/sh
#autostart

#polybar
killall -q polybar 
polybar -r yumeka-bar &

#wallpaper
~/.fehbg &

#set cursor
xsetroot -cursor_name left_ptr &

#open neovim at launch
if pgrep -x nvim > /dev/null; then
	echo "neovim is running"	
else
	alacritty -e nvim -c VimwikiIndex &
fi
