#! /bin/sh

#bspwm rule cause i don't want a config full of clutter

#autostarting apps launch location
bspc rule -a Brave-browser	desktop = '2'
bspc rule -a Steam		desktop	= '3'
bspc rule -a Discord		desktop	= '4'
bspc rule -a Krita		desktop	= '5'
bspc rule -a Todoist			desktop	= '6'
bspc rule -a mpv		desktop = '7'	follow = on
bspc rule -a Whatsdesk		desktop	= '8'
bspc rule -a spotify		desktop = '9'

#frequently used apps rule
bspc rule -a Pavucontrol	state = floating
bspc rule -a genshinimpact.exe	state = floating
