#!/bin/sh

# Set the desktop that should be floating
FLOATING_DESKTOP_ID=$(bspc query -D -d '^9') 

# subscribe to the node_add event, read all messages and execute following for each one
bspc subscribe node_add | while read -a msg ; do 
  desk_id=${msg[2]} # get desktop id from event message
  wid=${msg[4]} # get window id from event message

  # compare desktop id from event message to the previously set id for the desktop that should be floating. If it matches set the newly spawned window to floating mode
  [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating 
done
