#! /bin/sh

#bspwm rule cause i don't want a config full of clutter

#autostarting apps launch location
bspc rule -a firefox				desktop = '2'
bspc rule -a discord				desktop	= '3'
bspc rule -a Steam				desktop	= '9'
bspc rule -a mpv				desktop = '2'
bspc rule -a qbittorrent			desktop = '6'

#frequently used apps rule
bspc rule -a Pavucontrol	state = floating
bspc rule -a genshinimpact.exe	state = floating
bspc rule -a anki		state = floating
