#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [ "$(xrandr | grep "HDMI-1 connected")" ]
then
	xrandr --output eDP-1 --off --output HDMI-1 --auto
		bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
else
	xrandr --output eDP-1 --auto --output HDMI-1 --off
		bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
fi

# Used to make polybar maintain proper workspaces per monitor when going from 2
# to 1 monitor again.. This may include some monitor re-ordering issues
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move

# Sometimes when using an external monitor that is larger than the base laptop
# screen size, padding would be applied to make the nodes the size of the
# laptop resolution - we don't want that, as the nodes should fill out the
# entire height/width of the monitor, so we set all padding to 0.
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 

#Focus on hover
bspc config focus_follows_pointer true

bspc config border_width         5
bspc config window_gap           10
bspc config split_ratio          0.52
bspc config active_border_color "#E23182"
bspc config focused_border_color "#E23182"

#Set desktop 1 to floating
exec $HOME/.config/bspwm/Floating_Desktop &

#bspwm rule
exec $HOME/.config/bspwm/bspwm_rule &

killall -q polybar
polybar -r yumeka-bar &

#compositor
picom --experimental-backends &

#autostart
exec $HOME/.config/bspwm/autostart &
