#!/bin/sh
exec waybar &


#app key
riverctl map normal Ctrl+Alt T spawn 'env LANG=en_US.UTF-8 kitty'
riverctl map normal Super D spawn #dmenu
riverctl map normal Super E spawn pcmanfm



#keybinds
riverctl map normal Super Q close
riverctl map normal Super+Shift Q exit

riverctl map normal Super F toggle-float
riverctl map normal Super+Shift F toggle-fullscreen


#window management
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100



#tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

done



#media keys
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl -- set-sink-volume 0 +5%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl -- set-sink-volume 0 -5%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl -- set-sink-mute 0 toggle'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl default-layout rivertile
