[colors]
background = #191919
foreground = #ffffff

[bar/yumeka-bar]
monitor = HDMI-1
monitor-fallback = eDP-1
fixed-center = true
height = 26
background = ${colors.background}
foreground = ${colors.foreground}
font-0 =
font-1 =

modules-left = bspwm xwindow

modules-right = pulseaudio battery clock

wm-name = bspwm

tray-position = right
tray-maxsize = 14
tray-foreground = ${colors.foreground}
enable-ipc = true

[module/bspwm]
type = internal/bspwm
pin-workspace = false
enable-click = true
enable-scroll = true
reverse-scroll = true

[module/title]
type = internal/xwindow

[module/pulseaudio]
type = internal/pulseaudio
interval = 1

[module/battery]
type = internal/battery
full-at = 99
low-at = 15
battery = BAT1
adapter = ACAD
poll-interval = 5

[module/date]
type = internal/date

; Seconds to sleep between updates
; Default: 1.0
interval = 1.0

; See "https://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = %Y-%m-%d%

; Optional time format
time = %H:%M
date-alt = %A, %d %B %Y
time-alt = %H:%M:%S
